services:
  - type: web
    name: equinox2025-backend
    env: node
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    plan: free
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 4000

